"""
Seed the database with realistic demo watch listings so the UI is
populated without having to run a live scrape first.
"""
import database as db

db.init_db()
source_id = db.get_source_id("RolexForums BST")

DEMO_LISTINGS = [
    {
        "source_id": source_id,
        "title": "[WTS] Rolex Datejust 116234 2007 Box & Papers - Excellent Condition",
        "brand": "Rolex",
        "model": "Datejust",
        "reference": "116234",
        "year": 2007,
        "price": 7800.0,
        "currency": "USD",
        "condition": "Excellent",
        "seller": "WatchCollector42",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000001",
        "description": "Selling my 2007 Rolex Datejust 116234 in excellent condition. "
                       "Comes with original box, papers, and all accessories. Two-tone "
                       "with jubilee bracelet. Just serviced by Rolex AD.",
        "image_url": None,
        "date_listed": "2024-01-15",
        "price_rating": "Good",
        "market_price": 8200.0,
        "price_delta_pct": 95.1,
        "watchcharts_url": "https://watchcharts.com/watches/116234-rolex-datejust",
    },
    {
        "source_id": source_id,
        "title": "[WTS] Rolex GMT-Master II 116710LN 2007 - Great Price!",
        "brand": "Rolex",
        "model": "GMT-Master II",
        "reference": "116710LN",
        "year": 2007,
        "price": 9500.0,
        "currency": "USD",
        "condition": "Very Good",
        "seller": "VintageLux",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000002",
        "description": "2007 Rolex GMT-Master II Black Ceramic Bezel. No scratches on case, "
                       "bracelet shows light wear. Papers present, no box. Price is firm.",
        "image_url": None,
        "date_listed": "2024-01-20",
        "price_rating": "Great",
        "market_price": 11200.0,
        "price_delta_pct": 84.8,
        "watchcharts_url": "https://watchcharts.com/watches/116710ln-rolex-gmt-master-ii",
    },
    {
        "source_id": source_id,
        "title": "FS: Rolex Submariner Date 16610 2007 Complete Set $10,500",
        "brand": "Rolex",
        "model": "Submariner",
        "reference": "16610",
        "year": 2007,
        "price": 10500.0,
        "currency": "USD",
        "condition": "Mint",
        "seller": "DiveWatchGuru",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000003",
        "description": "Beautiful 2007 Submariner Date. Purchased new from AD, worn sparingly. "
                       "Full set: box, papers, hang tags, warranty card. No service needed.",
        "image_url": None,
        "date_listed": "2024-01-22",
        "price_rating": "Fair",
        "market_price": 9800.0,
        "price_delta_pct": 107.1,
        "watchcharts_url": "https://watchcharts.com/watches/16610-rolex-submariner-date",
    },
    {
        "source_id": source_id,
        "title": "[WTS] Rolex Daytona 116520 2007 White Dial SS - $18,500",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "116520",
        "year": 2007,
        "price": 18500.0,
        "currency": "USD",
        "condition": "Excellent",
        "seller": "ChronographKing",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000004",
        "description": "2007 Rolex Daytona stainless steel with white dial. "
                       "Box and papers. Serviced 2022. One of the last 4-liner dials.",
        "image_url": None,
        "date_listed": "2024-01-25",
        "price_rating": "High",
        "market_price": 15500.0,
        "price_delta_pct": 119.4,
        "watchcharts_url": "https://watchcharts.com/watches/116520-rolex-daytona",
    },
    {
        "source_id": source_id,
        "title": "[WTS] Rolex Datejust 116200 2007 Blue Dial Oyster Bracelet",
        "brand": "Rolex",
        "model": "Datejust",
        "reference": "116200",
        "year": 2007,
        "price": 6200.0,
        "currency": "USD",
        "condition": "Good",
        "seller": "ClassicTimepieces",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000005",
        "description": "2007 Datejust with stunning blue dial. Oyster bracelet, "
                       "no box no papers. Some scratches on bracelet. Great daily wearer.",
        "image_url": None,
        "date_listed": "2024-01-28",
        "price_rating": "Great",
        "market_price": 7400.0,
        "price_delta_pct": 83.8,
        "watchcharts_url": "https://watchcharts.com/watches/116200-rolex-datejust",
    },
    {
        "source_id": source_id,
        "title": "WTS Omega Seamaster Planet Ocean 2007 - $2,800 OBO",
        "brand": "Omega",
        "model": "Seamaster Planet Ocean",
        "reference": "2900.50",
        "year": 2007,
        "price": 2800.0,
        "currency": "USD",
        "condition": "Very Good",
        "seller": "OmegaFan007",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000006",
        "description": "2007 Omega Seamaster Planet Ocean 45mm. Co-axial movement, "
                       "ceramic bezel. Comes with box and papers. Minor bracelet wear.",
        "image_url": None,
        "date_listed": "2024-01-30",
        "price_rating": "Good",
        "market_price": 2950.0,
        "price_delta_pct": 94.9,
        "watchcharts_url": "https://watchcharts.com/watches/omega-seamaster-planet-ocean",
    },
    {
        "source_id": source_id,
        "title": "[WTS] Rolex Explorer II 16570 2007 White Dial",
        "brand": "Rolex",
        "model": "Explorer",
        "reference": "16570",
        "year": 2007,
        "price": 7900.0,
        "currency": "USD",
        "condition": "Excellent",
        "seller": "ExplorerEnthusiast",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000007",
        "description": "2007 Explorer II with white polar dial. Recently polished "
                       "by Rolex. Box and papers. Gorgeous example.",
        "image_url": None,
        "date_listed": "2024-02-01",
        "price_rating": "Good",
        "market_price": 8100.0,
        "price_delta_pct": 97.5,
        "watchcharts_url": "https://watchcharts.com/watches/16570-rolex-explorer-ii",
    },
    {
        "source_id": source_id,
        "title": "FS: Tudor Black Bay 2015 - $2,200 Complete",
        "brand": "Tudor",
        "model": "Black Bay",
        "reference": "79220R",
        "year": 2015,
        "price": 2200.0,
        "currency": "USD",
        "condition": "Excellent",
        "seller": "TudorTime",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000008",
        "description": "2015 Tudor Black Bay in burgundy. Box and papers, "
                       "wrist time only, no scratches. Great alternative to Submariner.",
        "image_url": None,
        "date_listed": "2024-02-02",
        "price_rating": None,
        "market_price": None,
        "price_delta_pct": None,
        "watchcharts_url": None,
    },
    {
        "source_id": source_id,
        "title": "[WTS] Rolex Datejust 116233 2007 Two-Tone Gold/Steel $9,200",
        "brand": "Rolex",
        "model": "Datejust",
        "reference": "116233",
        "year": 2007,
        "price": 9200.0,
        "currency": "USD",
        "condition": "Mint",
        "seller": "GoldAndSteel",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000009",
        "description": "Stunning two-tone 2007 Datejust. Gold/steel case and jubilee "
                       "bracelet. Champagne dial. Complete set with all paperwork.",
        "image_url": None,
        "date_listed": "2024-02-04",
        "price_rating": "Fair",
        "market_price": 8900.0,
        "price_delta_pct": 103.4,
        "watchcharts_url": "https://watchcharts.com/watches/116233-rolex-datejust",
    },
    {
        "source_id": source_id,
        "title": "WTS Patek Philippe Aquanaut 5167A 2019 - $28,000",
        "brand": "Patek Philippe",
        "model": "Aquanaut",
        "reference": "5167A",
        "year": 2019,
        "price": 28000.0,
        "currency": "USD",
        "condition": "Excellent",
        "seller": "HorologicalHaven",
        "listing_url": "https://www.rolexforums.com/showthread.php?t=1000010",
        "description": "2019 Patek Aquanaut in excellent condition. Box and papers. "
                       "One of the most versatile sports watches ever made.",
        "image_url": None,
        "date_listed": "2024-02-05",
        "price_rating": None,
        "market_price": None,
        "price_delta_pct": None,
        "watchcharts_url": None,
    },
]

added = 0
for listing in DEMO_LISTINGS:
    _, is_new = db.upsert_listing(listing)
    if is_new:
        added += 1

print(f"Seeded {added} demo listings ({len(DEMO_LISTINGS) - added} already existed).")
print(db.get_stats())
